### ISSUE TITLE
Skip stapling for a ZIP archive

### ISSUE THREAD

**Issue by Aleksid1** [rednoah/notarize-app#2]
It's possible to notarize DMG, PKG or ZIP archive. However ZIP archive with an APP bundle cannot be stapled after notarization. Can you modify your script to skip stapling of a ZIP archive? In this case, I staple original APP folder after notarization when you script finish it's job.
P.S. Thanks for your very useful script!

**Comment by rednoah** [comment]
For the sake of simplicity, custom logic for ZIP archives that contain APP bundles is not planned. You can always call `notarize-app` on your APP bundle before creating a DMG / PKG / ZIP archive though.
