### ISSUE TITLE
check status of two notarizations at the same time?

### ISSUE THREAD

**Issue by DominusExult** [rednoah/notarize-app#3]
It's a great and easy to understand script. Thanks a lot!

Now I'm wondering if this can be modified to check the status of two notarizations.
We are creating two apps from the same code at the same time. So I'm running the notarization one after the other but wonder if it is possible to check on their status in parallel.

**Comment by rednoah** [comment]
For the sake of simplicity, parallel processing is not planned. You can always call `notarize-app` in parallel though.
https://www.cyberciti.biz/faq/how-to-run-command-or-code-in-parallel-in-bash-shell-under-linux-or-unix/

**Comment by DominusExult** [comment]
I'll dig into parallel calling, thanks for the link!
